/**
 * Hand-curated unique content per region. Kept SEPARATE from regions.json (which is
 * auto-regenerated by scripts/build-regions.js) so it survives every rebuild.
 *
 * Keyed by region slug — must match the `slug` field in regions.json. The page template
 * (app/[slug]/page.tsx) merges this in at render time. Missing slugs render the
 * generic template without an error.
 *
 * Editorial rule: only include claims that can be verified from a primary or near-primary
 * source (planning authority's website, gazette notification, Wikipedia citing a primary).
 * When in doubt, omit. Each entry below was researched against the sources listed inline.
 */

export type RegionQuickFact = { label: string; value: string };

export type RegionContent = {
  // 1-3 paragraphs of unique prose. Aim 150-300 words combined.
  paragraphs: string[];
  // Structured "key facts" displayed alongside the prose.
  quickFacts: RegionQuickFact[];
};

export const REGION_CONTENT: Record<string, RegionContent> = {
  // Sources: pmc.gov.in DP-Plan, Notification TPS-1815/209/CR-69/15/D.P.Pune/Sanction/UD-13,
  // Government Notification No TPS-1818/CR-85/18/UD-13 dated 08.03.2019, MIDC portal.
  'pune-dp-plan': {
    paragraphs: [
      'The Pune Development Plan is administered by the Pune Municipal Corporation (PMC). The Development Control and Promotion Regulations (DCPR) governing land use and building activities within PMC limits were sanctioned by the Maharashtra State Government on 5 January 2017, and the formal gazette notification for the sanctioned Development Plan of the old PMC limits was issued on 8 March 2019. The plan applies to building activities within the area first notified under Section 23 of the Maharashtra Regional and Town Planning Act, 1966 on 13 December 2007.',
      "Pune's planning is split between two authorities: PMC handles the city core, while the Pune Metropolitan Region Development Authority (PMRDA) covers the broader metropolitan periphery — including the high-growth fringe villages and Town Planning Schemes outside PMC limits.",
      'Major industrial and growth anchors in and around the PMC area include the Pimpri-Chinchwad Municipal Corporation (PCMC) industrial complex with its Bhosari and Chinchwad MIDC estates, the Hinjewadi Rajiv Gandhi Infotech Park (around 2,800 acres hosting over 800 IT companies), and connectivity provided by the Mumbai-Pune Expressway (NH-48) and the Pune Ring Road. The DP map on this page reflects these zoning, road and reservation boundaries as published by PMC, overlaid on satellite imagery so plot boundaries align with on-ground features.',
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Pune Municipal Corporation (PMC)' },
      { label: 'DCPR sanctioned', value: '5 January 2017' },
      { label: 'Gazette notification (old limits)', value: '8 March 2019' },
      { label: 'Governing Act', value: 'Maharashtra Regional and Town Planning Act, 1966' },
      { label: 'Adjacent metropolitan authority', value: 'PMRDA (Pune Metropolitan Region Development Authority)' },
      { label: 'Key industrial clusters', value: 'Hinjewadi IT Park, Bhosari MIDC, PCMC' },
    ],
  },

  // Sources: MCGM DCPR 2034 PDF, Notification dated 8 May 2018, Wikipedia (WEH/EEH).
  'mumbai-western-suburbs-dp-plan': {
    paragraphs: [
      'The Mumbai Western Suburbs Development Plan is part of the Greater Mumbai DP 2034, the master plan for all 24 wards of Mumbai prepared by the Municipal Corporation of Greater Mumbai (MCGM). The State Government accorded sanction to the DP 2034 (with modifications) by notification dated 8 May 2018; the plan remains in force until 2034 and is implemented alongside the Development Control and Promotion Regulations (DCPR) 2034.',
      'The Western Suburbs cover the area from Bandra in the south to Dahisar in the north, encompassing wards H/W, K/E, K/W, P/N, P/S, R/N, R/C and R/S. The spine of the suburbs is the Western Express Highway (WEH) — an 8-to-10-lane arterial running approximately 25.3 km from Bandra to Mira Road via Andheri, Jogeshwari, Goregaon, Malad and Borivali — connecting directly to the Chhatrapati Shivaji Maharaj International Airport. Major east-west connectors carried in the plan include the Jogeshwari-Vikhroli Link Road (JVLR) and the Santa Cruz-Chembur Link Road (SCLR).',
      'Zoning across the Western Suburbs handles a dense mix of residential, commercial, transit-oriented and industrial uses, including the Bandra-Kurla Complex (BKC) commercial district within Bandra East. The DP overlay on this page is sourced from MCGM’s published plan and shows zoning boundaries aligned with satellite imagery.',
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Municipal Corporation of Greater Mumbai (MCGM)' },
      { label: 'Plan sanctioned', value: '8 May 2018 (DP 2034 with modifications)' },
      { label: 'Plan validity', value: 'Until 2034' },
      { label: 'Governing regulations', value: 'DCPR 2034' },
      { label: 'Primary arterial', value: 'Western Express Highway (~25.3 km)' },
      { label: 'Key commercial node', value: 'Bandra-Kurla Complex (BKC)' },
    ],
  },

  'mumbai-eastern-suburbs-dp-plan': {
    paragraphs: [
      'The Mumbai Eastern Suburbs Development Plan is part of the Greater Mumbai DP 2034, sanctioned by the Maharashtra State Government on 8 May 2018 and prepared by the Municipal Corporation of Greater Mumbai (MCGM). The Eastern Suburbs cover the corridor from Sion northwards through Kurla, Ghatkopar, Vikhroli, Bhandup and Mulund, spanning major wards L, N and S.',
      'The principal spine of the Eastern Suburbs is the Eastern Express Highway (EEH) — a six-lane arterial running approximately 23.55 km from Chhatrapati Shivaji Maharaj Terminus to Thane, connecting onward to National Highway 3 towards Nashik and Agra. The Eastern Freeway provides an additional grade-separated link from the Island City. Critical east-west connectors include the Jogeshwari-Vikhroli Link Road (JVLR) and the Santa Cruz-Chembur Link Road (SCLR) tying the suburbs across to the Western Suburbs.',
      'The Eastern Suburbs host significant industrial and warehousing land — historically textile and engineering hubs in Kurla and Ghatkopar — and the DP 2034 carries reservations for metro rail alignments, public amenities and Transit-Oriented Development along Mumbai Metro Line 4 and the suburban Central Railway corridor. The overlay on this page reflects these published zoning, road and amenity reservations from MCGM georeferenced over satellite imagery.',
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Municipal Corporation of Greater Mumbai (MCGM)' },
      { label: 'Plan sanctioned', value: '8 May 2018 (DP 2034)' },
      { label: 'Plan validity', value: 'Until 2034' },
      { label: 'Primary arterial', value: 'Eastern Express Highway (~23.55 km)' },
      { label: 'Connecting national highway', value: 'NH-3 (towards Nashik / Agra)' },
      { label: 'Major metro line carried', value: 'Mumbai Metro Line 4 (Wadala-Kasarvadavli)' },
    ],
  },

  'mumbai-internal-island-city-dp-plan': {
    paragraphs: [
      'The Mumbai Internal Island City Development Plan is the core component of the Greater Mumbai DP 2034, sanctioned by the Maharashtra State Government on 8 May 2018 and prepared by the Municipal Corporation of Greater Mumbai (MCGM). The Island City covers wards A through G/South — Mumbai’s historic southern peninsula — and is governed by the Development Control and Promotion Regulations (DCPR) 2034 valid till the year 2034.',
      'The Island City stretches from Colaba in the south to Mahim and Sion in the north, encompassing historic precincts of Fort, Marine Drive, Worli, Dadar, Mahim and Mazgaon. The two principal arterials beginning from the city core are the Western Express Highway (which starts near Mahim Creek) and the Eastern Express Highway (which originates near CSMT). The Eastern Freeway, an elevated six-lane corridor, provides a high-speed exit from the southern peninsula to the Eastern Suburbs.',
      'Island City planning carries a dense mix of heritage-zone overlays, commercial Central Business Districts (Nariman Point, Fort, Lower Parel), redevelopment cluster zones over former mill lands, and reservations for amenity uses. The DP 2034 includes significant Transit-Oriented Development around the Mumbai Metro Line 3 (Aqua Line) corridor running from Cuffe Parade to Aarey. The overlay on this page reflects these zoning and reservation boundaries from MCGM, georeferenced against satellite imagery.',
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Municipal Corporation of Greater Mumbai (MCGM)' },
      { label: 'Plan sanctioned', value: '8 May 2018 (DP 2034)' },
      { label: 'Plan validity', value: 'Until 2034' },
      { label: 'Key business districts', value: 'Nariman Point, Fort, BKC-adjacent, Lower Parel' },
      { label: 'Major redevelopment overlay', value: 'Mill lands cluster scheme' },
      { label: 'Transit-oriented corridor', value: 'Mumbai Metro Line 3 (Aqua Line)' },
    ],
  },

  // Sources: TMC DCR 1994, MMRDA 27-villages report, Wagle Estate Wikipedia, Thane DP 2026-2046 reporting.
  'thane-dp-plan': {
    paragraphs: [
      'The Thane Development Plan is administered by the Thane Municipal Corporation (TMC). The principal Development Plan was sanctioned by the Maharashtra State Government on 4 October 1999, with the excluded part sanctioned on 3 April 2003; the consolidated plan came into force from 14 May 2003. A revised Thane DP 2026-2046 has been notified in draft and is currently in the public-objections and revision stage at TMC.',
      "Thane's industrial backbone is centred on the Wagle Industrial Estate — established by the Maharashtra Industrial Development Corporation in 1962, this was MIDC’s first industrial estate in the state. It hosts a mix of engineering, electronics, pharma, IT and BPO operations and is anchored by the Eastern Express Highway, directly accessible from Mumbai via Mulund and Bhandup.",
      "The major arterial network in the TMC plan includes the Eastern Express Highway, the Thane-Belapur Road (linking Navi Mumbai and Airoli), and Ghodbunder Road which carries the city's western growth corridor towards Borivali, Mira-Bhayandar and the Mumbai-Nashik Highway. Mumbai Metro Line 4 (Wadala-Kasarvadavli) runs along the Eastern Express Highway with stations serving Thane; Line 5 (Thane-Bhiwandi-Kalyan) extends the metro network east into the KDMC area.",
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Thane Municipal Corporation (TMC)' },
      { label: 'Plan sanctioned (principal)', value: '4 October 1999' },
      { label: 'Excluded-part sanction', value: '3 April 2003' },
      { label: 'In force from', value: '14 May 2003' },
      { label: 'Successor plan (draft)', value: 'Thane DP 2026-2046' },
      { label: 'Key industrial estate', value: 'Wagle Estate (MIDC, est. 1962)' },
      { label: 'Major growth corridor', value: 'Ghodbunder Road' },
    ],
  },

  // Sources: nmc.gov.in DP page, Section 26 report, DCPR 2015, MIDC portal.
  'nashik-dp-plan': {
    paragraphs: [
      'The Nashik Development Plan is administered by the Nashik Municipal Corporation (NMC), which was constituted on 7 November 1982 under the Maharashtra Regional and Town Planning Act, 1966. The original Development Plan for NMC’s jurisdiction was sanctioned by the Maharashtra State Government in two parts — partly in 1993 and the remainder in 1994. A Revised Sanctioned Development Plan along with the Development Control and Promotion Regulations was sanctioned partly in 2017 and the remaining part in 2018.',
      "Nashik's industrial growth is anchored by three principal MIDC industrial estates — Satpur, Ambad and Sinnar — with additional industrial activity at Malegaon and Igatpuri elsewhere in the district. The Satpur and Ambad estates host engineering, pharmaceutical, automotive, sugar, textile, chemical and food-processing units, with main carriageway widths of 45 m and internal roads of 20-25 m.",
      'The principal connectivity spine for Nashik city and its industrial estates is National Highway 3, the Mumbai-Agra Highway, which runs east-west through the city and links Nashik directly to Mumbai (around 165 km southwest) and to Aurangabad and Agra to the north. The DP overlay on this page reflects NMC’s sanctioned zoning, reservation and road-line boundaries georeferenced over satellite imagery.',
    ],
    quickFacts: [
      { label: 'Planning authority', value: 'Nashik Municipal Corporation (NMC)' },
      { label: 'NMC constituted', value: '7 November 1982' },
      { label: 'Original DP sanctioned', value: '1993 (part) and 1994 (remainder)' },
      { label: 'Revised DP sanctioned', value: '2017 (part) and 2018 (remainder)' },
      { label: 'Governing regulations', value: 'DCPR 2015' },
      { label: 'Key MIDC estates', value: 'Satpur, Ambad, Sinnar' },
      { label: 'Primary national highway', value: 'NH-3 (Mumbai-Agra)' },
    ],
  },

  // Sources: nmrda.org, NIT Nagpur DCR 2018 PDF, Butibori MIDC profile, Wikipedia NMRDA.
  'nagpur-metropolitan-region-dp-plan': {
    paragraphs: [
      'The Nagpur Metropolitan Region Development Plan covers approximately 3,567 square kilometres encompassing 721 villages across 9 tehsils of Nagpur District. The plan was prepared by the Nagpur Improvement Trust (NIT) acting as the Special Planning Authority under the Maharashtra Regional and Town Planning Act, 1966, and is administered by the Nagpur Metropolitan Region Development Authority (NMRDA). The plan covers the period 2012-2032, and the associated Development Control and Promotion Regulations were notified in 2018.',
      'Major industrial anchors in the metropolitan region include the Butibori MIDC Industrial Estate, located approximately 25 km east of Nagpur city. Established in 1994 and covering around 23 square kilometres, Butibori is one of Asia’s largest planned industrial estates and was envisioned to support ancillary industries to the adjacent MIHAN (Multimodal International Cargo Hub and Airport at Nagpur) project. MIHAN itself integrates international air cargo, a Special Economic Zone, and warehousing close to the Nagpur airport.',
      'Nagpur sits at the junction of two Asian Highways — AH-43 (Agra to Matara, Sri Lanka) and AH-46 (Kharagpur to Dhule) — and is also served by national highways NH-44 and NH-53, giving the metropolitan region direct connectivity to Mumbai, Delhi, Kolkata and Hyderabad. The DP overlay on this page reflects the NMRDA-administered zoning, road and reservation boundaries georeferenced over satellite imagery.',
    ],
    quickFacts: [
      { label: 'Planning authority (plan-preparation)', value: 'Nagpur Improvement Trust (NIT)' },
      { label: 'Administering authority', value: 'Nagpur Metropolitan Region Development Authority (NMRDA)' },
      { label: 'Plan period', value: '2012-2032' },
      { label: 'DCPR notified', value: '2018' },
      { label: 'Coverage', value: '~3,567 sq km, 721 villages across 9 tehsils' },
      { label: 'Key industrial estate', value: 'Butibori MIDC (est. 1994, ~23 sq km)' },
      { label: 'Adjacent integrated project', value: 'MIHAN (cargo hub + SEZ)' },
      { label: 'Asian highways at junction', value: 'AH-43 and AH-46' },
    ],
  },
};

/** Look up unique content by region slug. Returns null when no curated content exists. */
export function regionContentBySlug(slug: string): RegionContent | null {
  return REGION_CONTENT[slug] ?? null;
}
