/**
 * Hand-curated SEO overrides for specific sub-location (/<region>/<loc>/) pages.
 *
 * Kept SEPARATE from regions.json (auto-regenerated by scripts/build-regions.js from
 * Firebase RTDB `menuGIS`) so it survives every rebuild — same pattern as
 * region-content.ts, but keyed by the FULL path "<regionSlug>/<villageSlug>".
 *
 * Most sub-location pages are fine with the generic template. Use this only when a
 * sub-location is itself a high-value search target whose templated title/keywords
 * don't match how people actually search for it (e.g. an acronym, or a "draft" plan
 * year). The page template (app/[slug]/[loc]/page.tsx) merges this in at render time;
 * any field left undefined falls back to the generic template. Missing keys render the
 * generic template with no error.
 *
 * Editorial rule (same as region-content.ts): only claims verifiable from a primary or
 * near-primary source. When in doubt, omit.
 *
 * Bulk machine-generated entries (research + adversarial verification, the 'dpplans-town-seo'
 * workflow) live in ./sublocation-content.generated.ts. The hand-curated SUBLOCATION_CONTENT
 * below ALWAYS takes precedence over the generated map at lookup time.
 */
import { GENERATED_SUBLOCATION_CONTENT } from './sublocation-content.generated';

export type SubLocationContent = {
  // Overrides <title>, OpenGraph/Twitter title, and the on-page <h1>.
  pageTitle?: string;
  // Overrides the <meta description> and OpenGraph/Twitter description.
  description?: string;
  // Replaces the generated keywords array (use the exact phrases people search).
  keywords?: string[];
  // Optional lead paragraph rendered before the generic "About …" prose.
  intro?: string;
  // Optional extra unique paragraphs appended after the intro.
  paragraphs?: string[];
};

export const SUBLOCATION_CONTENT: Record<string, SubLocationContent> = {
  // PCMC now has its OWN top-level hub at /pcmc-development-plan/ which owns the
  // "pcmc draft development plan" head term (Easy / >1000-volume, Ahrefs). To stop the
  // two PCMC pages cannibalising each other, this in-Pune sub-location page is re-pointed
  // at the locality long-tail (Bhosari / Chinchwad / Akurdi / Nigdi) with prose kept
  // distinct from the hub. The DP layer we host is named "(Draft 2025)" in menuGIS.
  'pune-dp-plan/pimpri-chinchwad-municipal-corporation': {
    pageTitle: 'Pimpri Chinchwad DP map online — PCMC draft plan zones & land use',
    description:
      'Open the PCMC Draft Development Plan (2025) on the map and read the proposed zone, reservations and road lines for Bhosari, Chinchwad, Pimpri, Akurdi, Nigdi-Pradhikaran and Wakad. See the dedicated PCMC Development Plan page for the full plan overview.',
    keywords: [
      'pimpri chinchwad dp map',
      'bhosari development plan',
      'chinchwad zoning map',
      'akurdi dp plan',
      'nigdi development plan',
      'pcmc land use map',
      'wakad development plan',
    ],
    intro:
      'This page opens the PCMC Draft Development Plan (2025) on the map, zoomed to the Pimpri-Chinchwad Municipal Corporation area in Pune district, Maharashtra. Use it to read the proposed land-use zone, reservations and road lines for specific localities in the twin city — pan and zoom over satellite imagery to trace any boundary on the ground.',
    paragraphs: [
      "Check the PCMC localities directly: the Bhosari (MIDC), Chinchwad, Pimpri and Akurdi industrial belts, and the residential and commercial growth around Nigdi-Pradhikaran, Sangvi, Wakad and Ravet along the Mumbai-Pune Expressway / old NH-48 corridor. The draft DP defines the residential, commercial, industrial, green and public-utility zones and the proposed road network across these areas; toggle the overlay to confirm the zone for any plot.",
      'For the full PCMC plan overview, key facts and FAQs see the dedicated PCMC Development Plan page, and for the adjoining city see the Pune (PMC) Development Plan. This is the draft plan — confirm the final sanctioned plan with PCMC before relying on a zone for any decision.',
    ],
  },

  // --- Pune (PMC) high-search city localities ---
  // Each of these pulls real "<locality> dp plan" + "<locality> dp plan pdf download"
  // search volume (Google Search Console). Curated here so they become indexable unique
  // pages (index,follow + sitemap) instead of the thin noindex village template, and so
  // they stop leaking impressions to the generic Pune page. Facts kept to widely-verifiable
  // locality identity; the DP framing (zones / reservations / DP road lines, DCPR 2017,
  // PMC limits, view-vs-download the official PMC sheets) is generic and source-safe.
  'pune-dp-plan/lohegaon': {
    pageTitle: 'Lohegaon DP Plan map online — PMC zones, DP road & land use, Pune',
    description:
      'View the Lohegaon section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery near Pune Airport — read the land-use zone, reservations and DP road lines for any plot in Lohegaon, north-east Pune.',
    keywords: [
      'lohegaon dp plan',
      'lohegaon dp plan map',
      'lohegaon development plan',
      'lohegaon dp road plan',
      'lohegaon dp plan pdf download',
      'lohegaon dp plan 2025',
      'lohegaon zoning map',
      'lohegaon pmc dp map',
    ],
    intro:
      'Lohegaon is a north-east Pune locality best known as the home of Pune International Airport (the Lohegaon airbase), on the Vishrantwadi–Dhanori side of the city within Pune Municipal Corporation (PMC) limits. This page opens the sanctioned Pune Development Plan zoomed to Lohegaon as an interactive overlay on satellite imagery, so you can read the land-use zone, public reservations and proposed DP road lines for any plot here.',
    paragraphs: [
      'Lohegaon has grown quickly as a residential and rental belt around the airport and the Dhanori–Vishrantwadi corridor, which makes the DP road alignments and road-widening lines through the area particularly worth checking before any plot decision — search by survey or CTS number and toggle the overlay to confirm whether a proposed road, reservation or zone boundary falls on the plot.',
      'PMC publishes the sanctioned DP sheets covering Lohegaon as PDFs on pmc.gov.in; rather than downloading and scanning a large sheet, you can read the same zone and DP remark for a specific plot directly on this map. Browsing Lohegaon is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/baner': {
    pageTitle: 'Baner DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Baner section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery along the Mumbai–Bangalore highway — read the land-use zone, reservations and DP road lines for any plot in Baner, north-west Pune.',
    keywords: [
      'baner dp plan',
      'baner development plan',
      'baner dp',
      'baner dp plan pdf download',
      'baner zoning map',
      'baner pmc dp map',
      'baner pune land use',
    ],
    intro:
      'Baner is a fast-growing IT and residential suburb in north-west Pune, alongside Aundh, Balewadi and Pashan and close to the Mumbai–Bangalore Highway (old NH-4), within Pune Municipal Corporation (PMC) limits and below the Baner–Pashan biodiversity hill. This page opens the sanctioned Pune Development Plan zoomed to Baner as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Rapid high-rise and office development along Baner Road and the highway service roads makes the DP zone and road-widening lines here worth confirming plot-by-plot — search a survey or CTS number and toggle the overlay to see the designated zone (residential, commercial, public-utility, green or no-development) and any reservation or DP road crossing it.',
      'PMC publishes the sanctioned DP sheets covering Baner as PDFs on pmc.gov.in; instead of downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Baner is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/kharadi': {
    pageTitle: 'Kharadi DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Kharadi section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery around the EON IT hub — read the land-use zone, reservations and DP road lines for any plot in Kharadi, east Pune.',
    keywords: [
      'kharadi dp plan',
      'kharadi development plan',
      'kharadi dp plan pdf download',
      'kharadi zoning map',
      'kharadi pmc dp map',
      'kharadi eon it park',
      'kharadi pune land use',
    ],
    intro:
      'Kharadi is a major east-Pune IT and commercial hub built around the EON Free Zone IT park and the World Trade Center, on the Nagar Road / Mundhwa–Kharadi corridor within Pune Municipal Corporation (PMC) limits, next to Wagholi and Chandan Nagar. This page opens the sanctioned Pune Development Plan zoomed to Kharadi as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'With dense IT-led office, hospitality and residential growth, Kharadi carries significant commercial zoning and several proposed road and road-widening lines — search a survey or CTS number and toggle the overlay to confirm the zone and whether a reservation or DP road falls on the plot before relying on it.',
      'PMC publishes the sanctioned DP sheets covering Kharadi as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Kharadi is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/dhanori': {
    pageTitle: 'Dhanori DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Dhanori section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery near Lohegaon and Vishrantwadi — read the land-use zone, reservations and DP road lines for any plot in Dhanori, north-east Pune.',
    keywords: [
      'dhanori dp plan',
      'dhanori development plan',
      'dhanori dp plan pdf download',
      'dhanori zoning map',
      'dhanori pmc dp map',
      'dhanori pune land use',
    ],
    intro:
      'Dhanori is a rapidly developing residential locality in north-east Pune, between Vishrantwadi, Lohegaon and Kalas, within Pune Municipal Corporation (PMC) limits. This page opens the sanctioned Pune Development Plan zoomed to Dhanori as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Heavy new housing along the Dhanori–Lohegaon and Dhanori–Kalas roads makes the DP road alignments and reservations here important to verify before buying or building — search a survey or CTS number and toggle the overlay to confirm the zone and any proposed road or reservation on the plot.',
      'PMC publishes the sanctioned DP sheets covering Dhanori as PDFs on pmc.gov.in; instead of downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Dhanori is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/balewadi': {
    pageTitle: 'Balewadi DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Balewadi section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery near the Shiv Chhatrapati Sports Complex — read the land-use zone, reservations and DP road lines for any plot in Balewadi, north-west Pune.',
    keywords: [
      'balewadi dp plan',
      'dp plan balewadi',
      'balewadi development plan',
      'balewadi dp plan pdf download',
      'balewadi zoning map',
      'balewadi pmc dp map',
      'balewadi stadium area',
    ],
    intro:
      'Balewadi is a north-west Pune locality known for the Shree Shiv Chhatrapati Sports Complex (Balewadi Stadium) and high-rise residential growth beside Baner and Wakad, within Pune Municipal Corporation (PMC) limits near the Mula river and the Mumbai–Bangalore highway. This page opens the sanctioned Pune Development Plan zoomed to Balewadi as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Balewadi has seen extensive township and high-rise development, so checking the DP zone and the proposed road-widening lines plot-by-plot matters — search a survey or CTS number and toggle the overlay to confirm the zone and any reservation or DP road crossing it.',
      'PMC publishes the sanctioned DP sheets covering Balewadi as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Balewadi is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/bavdhan': {
    pageTitle: 'Bavdhan DP Plan map online — zones & land use, Pune',
    description:
      'View the Bavdhan section of the Pune Development Plan online. Interactive DP overlay on satellite imagery near Chandni Chowk and Kothrud — read the land-use zone, reservations and DP road lines for any plot in Bavdhan (Khurd & Budruk), west Pune.',
    keywords: [
      'bavdhan dp plan',
      'bavdhan khurd dp plan',
      'bavdhan development plan',
      'bavdhan dp plan pdf download',
      'bavdhan zoning map',
      'bavdhan pune land use',
    ],
    intro:
      'Bavdhan is a west-Pune residential suburb near Chandni Chowk, Kothrud, Pashan and the NDA hills, split between Bavdhan Khurd and Bavdhan Budruk along the Mumbai–Bangalore bypass. This page opens the sanctioned Development Plan zoomed to Bavdhan as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Because parts of Bavdhan have developed across the Pune Municipal Corporation limit and the adjoining metropolitan periphery, confirming the exact zone and any proposed road line for a specific plot is especially worthwhile — search a survey number and toggle the overlay to read the designated zone and any reservation or DP road on it.',
      'The sanctioned DP sheets covering Bavdhan are published as PDFs by the planning authority; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Bavdhan is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day access pass.',
    ],
  },
  'pune-dp-plan/hadapsar': {
    pageTitle: 'Hadapsar DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Hadapsar section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery around Magarpatta and the industrial estate — read the land-use zone, reservations and DP road lines for any plot in Hadapsar, south-east Pune.',
    keywords: [
      'hadapsar dp plan',
      'hadapsar development plan',
      'hadapsar dp plan pdf download',
      'hadapsar zoning map',
      'hadapsar pmc dp map',
      'magarpatta hadapsar',
      'hadapsar industrial estate',
    ],
    intro:
      'Hadapsar is a large south-east Pune locality on the Solapur Road corridor, home to Magarpatta City, Amanora and the Hadapsar Industrial Estate, within Pune Municipal Corporation (PMC) limits. This page opens the sanctioned Pune Development Plan zoomed to Hadapsar as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Hadapsar mixes industrial, IT-township, commercial and residential land, so the DP zone and the proposed road-widening lines vary sharply across the area — search a survey or CTS number and toggle the overlay to confirm the designated zone and whether a reservation or DP road falls on the plot.',
      'PMC publishes the sanctioned DP sheets covering Hadapsar as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Hadapsar is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/wadgaon-sheri': {
    pageTitle: 'Vadgaon Sheri DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Vadgaon Sheri (Wadgaon Sheri) section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery near Kalyani Nagar and Viman Nagar — read the land-use zone, reservations and DP road lines for any plot, east Pune.',
    keywords: [
      'vadgaon sheri dp plan',
      'wadgaon sheri dp plan',
      'vadgaon sheri dp plan pdf download',
      'vadgaon sheri development plan',
      'vadgaon sheri zoning map',
      'vadgaon sheri pmc',
    ],
    intro:
      'Vadgaon Sheri (also spelt Wadgaon Sheri) is an east-central Pune locality next to Kalyani Nagar, Viman Nagar and Kharadi, within Pune Municipal Corporation (PMC) limits. This page opens the sanctioned Pune Development Plan zoomed to Vadgaon Sheri as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Sitting between established residential pockets and the IT belt, Vadgaon Sheri carries a mix of residential and commercial zoning with several proposed road lines — search a survey or CTS number and toggle the overlay to confirm the zone and any reservation or DP road on the plot.',
      'PMC publishes the sanctioned DP sheets covering Vadgaon Sheri as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing the area is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/katraj': {
    pageTitle: 'Katraj DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Katraj section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery along the Katraj–Kondhwa road and Katraj ghat — read the land-use zone, reservations and DP road lines for any plot in Katraj, south Pune.',
    keywords: [
      'katraj dp plan',
      'katraj dp plan pdf download',
      'katraj development plan',
      'katraj zoning map',
      'katraj pmc dp map',
      'katraj kondhwa road',
      'katraj pune land use',
    ],
    intro:
      'Katraj is a south-Pune locality known for Katraj Lake, the Rajiv Gandhi Zoological Park, the Katraj Dairy and the Katraj ghat on the old Pune–Satara road (NH-48), within Pune Municipal Corporation (PMC) limits next to Dhankwadi and Kondhwa. This page opens the sanctioned Pune Development Plan zoomed to Katraj as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Katraj rises into hill slopes towards the ghat and the inner ring road, so zones shift between developable, green and hill / no-development bands across short distances — search a survey or CTS number and toggle the overlay to confirm the exact zone and any reservation or DP road on the plot before relying on it.',
      'PMC publishes the sanctioned DP sheets covering Katraj as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Katraj is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },
  'pune-dp-plan/dhayari': {
    pageTitle: 'Dhayari DP Plan map online — PMC zones & land use, Pune',
    description:
      'View the Dhayari section of the Pune (PMC) Development Plan online. Interactive DP overlay on satellite imagery off Sinhagad Road — read the land-use zone, reservations and DP road lines for any plot in Dhayari, south-west Pune.',
    keywords: [
      'dhayari dp plan',
      'dhayari development plan',
      'dhayari dp plan pdf download',
      'dhayari zoning map',
      'dhayari sinhagad road',
      'dhayari pune land use',
    ],
    intro:
      'Dhayari is a south-west Pune residential locality off Sinhagad Road, near Narhe and on the approach towards Sinhagad fort, within Pune Municipal Corporation (PMC) limits. This page opens the sanctioned Pune Development Plan zoomed to Dhayari as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and proposed DP road lines for any plot.',
    paragraphs: [
      'Dhayari has filled in rapidly with residential development off Sinhagad Road, which makes the proposed DP road and road-widening lines worth checking plot-by-plot — search a survey or CTS number and toggle the overlay to confirm the zone and any reservation or DP road on the plot.',
      'PMC publishes the sanctioned DP sheets covering Dhayari as PDFs on pmc.gov.in; rather than downloading a large sheet, you can read the same zone and DP remark for a specific plot here. Browsing Dhayari is free up to zoom level 14; the higher-detail DP tiles unlock with a 7-day Pune access pass.',
    ],
  },

  // --- Solapur district: notable towns (taluka HQs / pilgrimage centres) ---
  // Curated so they read as unique pages (not the 95%-identical village template) and
  // become indexable. Each entry sticks to widely-verifiable facts; the DP head term
  // for Pandharpur is intentionally avoided in titles (it's saturated by the 2026 govt
  // corridor news + the Pandharpur Development Authority Act) in favour of map/zone intent.
  'solapur-dp-plan/pandharpur': {
    pageTitle: 'Pandharpur DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Pandharpur, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around the Pandharpur temple town and the Chandrabhaga riverfront.',
    keywords: [
      'pandharpur dp plan',
      'pandharpur development plan map',
      'pandharpur zoning map',
      'pandharpur land use map',
      'pandharpur development plan online',
      'pandharpur solapur map',
    ],
    intro:
      'Pandharpur is a temple town on the banks of the Bhima river — locally the Chandrabhaga — in Solapur district, Maharashtra, best known as the seat of the Vitthal-Rukmini temple and the destination of the Ashadhi and Kartiki Wari pilgrimages. This page opens the Development Plan layer covering Pandharpur as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road alignment for any plot in and around the town.',
    paragraphs: [
      'Because Pandharpur draws very large pilgrim crowds, planning around the temple core, the Chandrabhaga ghats and the approach roads carries particular weight. Pan and zoom on the map above to trace any zone boundary, reservation or proposed road line against the current ground imagery.',
      'Pandharpur lies roughly 41 km west of Solapur city. Use the search bar inside the full map to jump to a specific survey number, ward or landmark, then turn on the DP overlay to confirm the designated zone — residential, commercial, public-utility, green or reserved — before relying on it for any plot decision.',
    ],
  },
  'solapur-dp-plan/akkalkot-tal-akkalkot': {
    pageTitle: 'Akkalkot DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Akkalkot, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around the Akkalkot temple town near the Karnataka border.',
    keywords: [
      'akkalkot dp plan',
      'akkalkot development plan map',
      'akkalkot zoning map',
      'akkalkot land use map',
      'akkalkot development plan online',
      'akkalkot solapur map',
    ],
    intro:
      'Akkalkot is a town and taluka headquarters in the south-east of Solapur district, Maharashtra, close to the Karnataka border, widely known as a pilgrimage centre associated with Shri Swami Samarth. This page opens the Development Plan layer covering Akkalkot as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      "Akkalkot sits about 57 km east of Solapur city. Steady pilgrim footfall around the temple precinct and the town's position on routes toward the Karnataka border both shape its growth. Pan and zoom on the map above to trace any zone boundary or proposed road against the current satellite imagery.",
      'Use the search bar inside the full map to jump to a survey number or landmark in Akkalkot, then switch on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/barshi': {
    pageTitle: 'Barshi DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Barshi, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Barshi town.',
    keywords: [
      'barshi dp plan',
      'barshi development plan map',
      'barshi zoning map',
      'barshi land use map',
      'barshi development plan online',
      'barshi solapur map',
    ],
    intro:
      'Barshi is a town and taluka headquarters in the north of Solapur district, Maharashtra, long known as a cotton-trading and textile centre and for the historic Bhagawant temple. This page opens the Development Plan layer covering Barshi as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      'Barshi lies about 59 km north of Solapur city and is one of the larger towns in the district. Pan and zoom on the map above to trace any zone boundary, reservation or proposed road against current ground imagery.',
      'Use the search bar inside the full map to jump to a survey number or landmark in Barshi, then turn on the DP overlay to confirm the designated zone — residential, commercial, industrial, green or reserved — before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/mangalwedha': {
    pageTitle: 'Mangalwedha DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Mangalwedha, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Mangalwedha town.',
    keywords: [
      'mangalwedha dp plan',
      'mangalvedha development plan map',
      'mangalwedha zoning map',
      'mangalwedha land use map',
      'mangalwedha development plan online',
      'mangalwedha solapur map',
    ],
    intro:
      'Mangalwedha is a town and taluka headquarters about 34 km south-west of Solapur city in Maharashtra, often called a "land of saints" for its association with figures such as Sant Damaji, and known for its jowar (sorghum) growing belt. This page opens the Development Plan layer covering Mangalwedha as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      'Pan and zoom on the map above to trace any zone boundary or proposed road line through Mangalwedha against the current ground imagery.',
      'Use the search bar inside the full map to jump to a survey number or landmark, then turn on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/madha': {
    pageTitle: 'Madha DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Madha, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Madha town.',
    keywords: [
      'madha dp plan',
      'madha development plan map',
      'madha zoning map',
      'madha land use map',
      'madha development plan online',
      'madha solapur map',
    ],
    intro:
      'Madha is a town and taluka headquarters in the north-west of Solapur district, Maharashtra, and gives its name to the Madha Lok Sabha constituency. This page opens the Development Plan layer covering Madha as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      'Madha lies about 42 km north-west of Solapur city. Pan and zoom on the map above to trace any zone boundary or proposed road against the current ground imagery.',
      'Use the search bar inside the full map to jump to a survey number or landmark in Madha, then turn on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/mohol': {
    pageTitle: 'Mohol DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Mohol, Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Mohol town.',
    keywords: [
      'mohol dp plan',
      'mohol development plan map',
      'mohol zoning map',
      'mohol land use map',
      'mohol development plan online',
      'mohol solapur map',
    ],
    intro:
      'Mohol is a town and taluka headquarters about 14 km north-west of Solapur city in Maharashtra, lying on the Solapur–Pune road and rail corridor — the closest taluka town to the district headquarters. This page opens the Development Plan layer covering Mohol as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      "Its proximity to Solapur city and its position on the main Pune corridor shape Mohol's growth. Pan and zoom on the map above to trace any zone boundary or proposed road against current ground imagery.",
      'Use the search bar inside the full map to jump to a survey number or landmark in Mohol, then turn on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/akluj-tal-malshiras': {
    pageTitle: 'Akluj DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Akluj, in Malshiras taluka of Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Akluj town.',
    keywords: [
      'akluj dp plan',
      'akluj development plan map',
      'akluj zoning map',
      'akluj malshiras map',
      'akluj land use map',
      'akluj solapur map',
    ],
    intro:
      "Akluj is a town in Malshiras taluka, in the west of Solapur district, Maharashtra, a commercial centre in the district's sugarcane and sugar-cooperative belt. This page opens the Development Plan layer covering Akluj as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.",
    paragraphs: [
      'Akluj lies in the western part of the district, well away from Solapur city, amid an irrigated sugarcane region. Pan and zoom on the map above to trace any zone boundary or proposed road against the current ground imagery.',
      'Use the search bar inside the full map to jump to a survey number or landmark in Akluj, then turn on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
  'solapur-dp-plan/kurduwadi-tal-madha': {
    pageTitle: 'Kurduwadi DP Plan map online — Development Plan zones & land use, Solapur',
    description:
      'See the Development Plan covering Kurduwadi, in Madha taluka of Solapur district, Maharashtra, online. Interactive DP overlay on satellite imagery — read the land-use zone, reservations and road lines for any plot in and around Kurduwadi town.',
    keywords: [
      'kurduwadi dp plan',
      'kurduwadi development plan map',
      'kurduwadi zoning map',
      'kurduwadi madha map',
      'kurduwadi land use map',
      'kurduwadi solapur map',
    ],
    intro:
      'Kurduwadi is a town in Madha taluka, Solapur district, Maharashtra, that grew around its railway junction on the Central Railway and the historic Barshi Light Railway. This page opens the Development Plan layer covering Kurduwadi as an interactive overlay on satellite imagery, so you can read the land-use zone, reservations and road lines for any plot in the town.',
    paragraphs: [
      "The railway junction and its associated yards have long anchored Kurduwadi's layout. Pan and zoom on the map above to trace any zone boundary or proposed road against the current ground imagery.",
      'Use the search bar inside the full map to jump to a survey number or landmark in Kurduwadi, then turn on the DP overlay to confirm the designated zone before relying on it for a plot decision.',
    ],
  },
};

/**
 * Look up SEO override content by region + village slug. Null when none is curated.
 * Hand-curated SUBLOCATION_CONTENT wins over the machine-generated map.
 */
export function subLocationContent(regionSlug: string, locSlug: string): SubLocationContent | null {
  const key = `${regionSlug}/${locSlug}`;
  return SUBLOCATION_CONTENT[key] ?? GENERATED_SUBLOCATION_CONTENT[key] ?? null;
}

/**
 * True when a sub-location has unique curated content (hand-written OR verified-generated) —
 * and is therefore worth indexing. Drives both the page's robots meta
 * (app/[slug]/[loc]/page.tsx) and sitemap inclusion (app/sitemap.ts) off a single source of
 * truth: add an entry and the page automatically becomes index,follow + re-enters the sitemap.
 */
export function isCuratedSubLocation(regionSlug: string, locSlug: string): boolean {
  const key = `${regionSlug}/${locSlug}`;
  return !!SUBLOCATION_CONTENT[key] || !!GENERATED_SUBLOCATION_CONTENT[key];
}
