/**
 * Hand-curated SEO overrides for specific sub-location (/<region>/<loc>/) pages.
 *
 * Kept SEPARATE from regions.json (auto-regenerated by scripts/build-regions.js from
 * Firebase RTDB `menuGIS`) so it survives every rebuild — same pattern as
 * region-content.ts, but keyed by the FULL path "<regionSlug>/<villageSlug>".
 *
 * Most sub-location pages are fine with the generic template. Use this only when a
 * sub-location is itself a high-value search target whose templated title/keywords
 * don't match how people actually search for it (e.g. an acronym, or a "draft" plan
 * year). The page template (app/[slug]/[loc]/page.tsx) merges this in at render time;
 * any field left undefined falls back to the generic template. Missing keys render the
 * generic template with no error.
 *
 * Editorial rule (same as region-content.ts): only claims verifiable from a primary or
 * near-primary source. When in doubt, omit.
 */

export type SubLocationContent = {
  // Overrides <title>, OpenGraph/Twitter title, and the on-page <h1>.
  pageTitle?: string;
  // Overrides the <meta description> and OpenGraph/Twitter description.
  description?: string;
  // Replaces the generated keywords array (use the exact phrases people search).
  keywords?: string[];
  // Optional lead paragraph rendered before the generic "About …" prose.
  intro?: string;
  // Optional extra unique paragraphs appended after the intro.
  paragraphs?: string[];
};

export const SUBLOCATION_CONTENT: Record<string, SubLocationContent> = {
  // PCMC — "pcmc draft development plan" is an Easy / >1000-volume query (Ahrefs).
  // The generic template titled this "Pimpri Chinchwad Municipal Corporation
  // Development Plan map — Pune district" — no acronym, no "draft", so it never
  // matched the query. The DP layer we host is named "(Draft 2025)" in menuGIS.
  'pune-dp-plan/pimpri-chinchwad-municipal-corporation': {
    pageTitle: 'PCMC Draft Development Plan 2025 — Pimpri Chinchwad DP map online',
    description:
      'View the PCMC Draft Development Plan (2025) for the Pimpri Chinchwad Municipal Corporation online. Interactive DP overlay over satellite imagery — identify proposed zones, reservations and road lines for any plot across Pimpri, Chinchwad, Bhosari, Akurdi and Nigdi.',
    keywords: [
      'pcmc draft development plan',
      'pcmc development plan',
      'pcmc dp plan 2025',
      'pimpri chinchwad development plan',
      'pimpri chinchwad dp map online',
      'pcmc zoning map',
      'pcmc draft dp 2025',
    ],
    intro:
      'The Pimpri-Chinchwad Municipal Corporation (PCMC) is the civic body and planning authority for the twin industrial city of Pimpri-Chinchwad in Pune district, Maharashtra, constituted in 1982 and operating under the Maharashtra Regional and Town Planning Act, 1966. This page renders the PCMC Draft Development Plan (2025) as an interactive overlay on satellite imagery, so you can read the proposed land-use zone, reservations and road alignment for any plot in the corporation area.',
    paragraphs: [
      "PCMC's land-use is anchored by its industrial estates — the Bhosari (MIDC) estate, along with the Chinchwad, Pimpri and Akurdi industrial belts — and by the residential and commercial growth around Nigdi-Pradhikaran, Wakad and the Mumbai-Pune Expressway / old NH-48 corridor. The draft DP defines the residential, commercial, industrial, green and public-utility zones and the proposed road network across these areas; pan and zoom on the map above to trace any boundary against the current ground imagery.",
    ],
  },
};

/** Look up SEO override content by region + village slug. Null when none is curated. */
export function subLocationContent(regionSlug: string, locSlug: string): SubLocationContent | null {
  return SUBLOCATION_CONTENT[`${regionSlug}/${locSlug}`] ?? null;
}
